
package com.mycompany.cujijw_tenecotajm_tragamonedas;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;


public class VistaTragamonedas extends javax.swing.JFrame {

    public VistaTragamonedas() {
        initComponents();
        panelCentral.add(columna1);
        panelCentral.add(columna2);
        panelCentral.add(columna3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        columna1 = new javax.swing.JLabel();
        columna2 = new javax.swing.JLabel();
        columna3 = new javax.swing.JLabel();
        btnIniciarTodos = new javax.swing.JButton();
        btnPararTodos = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tiempoColumna1 = new javax.swing.JTextField();
        tiempoColumna2 = new javax.swing.JTextField();
        tiempoColumna3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnIniciarColumna1 = new javax.swing.JButton();
        btnPararColumna1 = new javax.swing.JButton();
        btnIniciarColumna2 = new javax.swing.JButton();
        btnPararColumna2 = new javax.swing.JButton();
        btnIniciarColumna3 = new javax.swing.JButton();
        btnPararColumna3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROGRAMA TRAGAMONEDAS");

        columna1.setText(" ");

        columna2.setText(" ");

        columna3.setText(" ");

        btnIniciarTodos.setBackground(new java.awt.Color(51, 255, 102));
        btnIniciarTodos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIniciarTodos.setText("INICIAR TODOS");
        btnIniciarTodos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPararTodos.setBackground(new java.awt.Color(255, 102, 0));
        btnPararTodos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPararTodos.setText("PARAR TODOS");
        btnPararTodos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelCentral.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelCentral.setLayout(new java.awt.GridLayout(1, 3));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("INDIQUE EL TIEMPO DE VELOCIDAD");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tiempoColumna1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tiempoColumna1.setText("100");

        tiempoColumna2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tiempoColumna2.setText("100");

        tiempoColumna3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tiempoColumna3.setText("100");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("INICIE POR SEPARADO CADA COLUMNA");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnIniciarColumna1.setBackground(new java.awt.Color(51, 255, 102));
        btnIniciarColumna1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIniciarColumna1.setText("INICIAR");
        btnIniciarColumna1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPararColumna1.setBackground(new java.awt.Color(255, 102, 0));
        btnPararColumna1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPararColumna1.setText("PARAR");
        btnPararColumna1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPararColumna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararColumna1ActionPerformed(evt);
            }
        });

        btnIniciarColumna2.setBackground(new java.awt.Color(51, 255, 102));
        btnIniciarColumna2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIniciarColumna2.setText("INICIAR");
        btnIniciarColumna2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPararColumna2.setBackground(new java.awt.Color(255, 102, 0));
        btnPararColumna2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPararColumna2.setText("PARAR");
        btnPararColumna2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnIniciarColumna3.setBackground(new java.awt.Color(51, 255, 102));
        btnIniciarColumna3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIniciarColumna3.setText("INICIAR");
        btnIniciarColumna3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPararColumna3.setBackground(new java.awt.Color(255, 102, 0));
        btnPararColumna3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPararColumna3.setText("PARAR");
        btnPararColumna3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPararColumna1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIniciarColumna1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnIniciarColumna2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnIniciarColumna3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnPararColumna2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPararColumna3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tiempoColumna1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(tiempoColumna2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tiempoColumna3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempoColumna1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoColumna2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoColumna3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarColumna1)
                    .addComponent(btnIniciarColumna2)
                    .addComponent(btnIniciarColumna3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPararColumna1)
                    .addComponent(btnPararColumna2)
                    .addComponent(btnPararColumna3))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIniciarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(btnPararTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(columna1)
                .addGap(29, 29, 29)
                .addComponent(columna2)
                .addGap(18, 18, 18)
                .addComponent(columna3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(columna1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(columna2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(columna3, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarTodos)
                    .addComponent(btnPararTodos))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPararColumna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararColumna1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPararColumna1ActionPerformed

    public JLabel getColumna1() { return columna1; }
    public JLabel getColumna2() { return columna2; }
    public JLabel getColumna3() { return columna3; }

    public JTextField getTiempoColumna1() { return tiempoColumna1; }
    public JTextField getTiempoColumna2() { return tiempoColumna2; }
    public JTextField getTiempoColumna3() { return tiempoColumna3; }

    public JButton getBtnIniciarColumna1() { return btnIniciarColumna1; }
    public JButton getBtnPararColumna1() { return btnPararColumna1; }

    public JButton getBtnIniciarColumna2() { return btnIniciarColumna2; }
    public JButton getBtnPararColumna2() { return btnPararColumna2; }

    public JButton getBtnIniciarColumna3() { return btnIniciarColumna3; }
    public JButton getBtnPararColumna3() { return btnPararColumna3; }

    public JButton getBtnIniciarTodos() { return btnIniciarTodos; }
    public JButton getBtnPararTodos() { return btnPararTodos; }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarColumna1;
    private javax.swing.JButton btnIniciarColumna2;
    private javax.swing.JButton btnIniciarColumna3;
    private javax.swing.JButton btnIniciarTodos;
    private javax.swing.JButton btnPararColumna1;
    private javax.swing.JButton btnPararColumna2;
    private javax.swing.JButton btnPararColumna3;
    private javax.swing.JButton btnPararTodos;
    private javax.swing.JLabel columna1;
    private javax.swing.JLabel columna2;
    private javax.swing.JLabel columna3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JTextField tiempoColumna1;
    private javax.swing.JTextField tiempoColumna2;
    private javax.swing.JTextField tiempoColumna3;
    // End of variables declaration//GEN-END:variables
}
