/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemapedidos.vistas;

import com.mycompany.sistemapedidos.conecctiondb.AdministradorDAO;
import com.mycompany.sistemapedidos.conecctiondb.EnsaladaDAO;
import com.mycompany.sistemapedidos.conecctiondb.PlatoDAO;
import com.mycompany.sistemapedidos.conecctiondb.SanducheDAO;
import com.mycompany.sistemapedidos.modelos.Plato;
import java.util.List;
import javax.swing.JOptionPane;

public class sistemaFrame extends javax.swing.JFrame {
    int id;
    /**
     * Creates new form sistemaFrame
     * @param id
     */
    public sistemaFrame(int id) {
        initComponents();
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA COME EN CASA");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\SistemaPedidos\\src\\main\\java\\com\\mycompany\\sistemapedidos\\vistas\\logo(1).png")); // NOI18N

        jMenu2.setText("Platos");

        jMenuItem3.setText("Almuerzo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Sanduches");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Ensaladas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        PlatoDAO platoDAO = new PlatoDAO();

        List<Plato> platos = platoDAO.obtenerPlatos();

        if (platos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se encontraron almuerzos.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            StringBuilder mensaje = new StringBuilder("Almuerzos:\n");
            for (Plato plato : platos) {
                mensaje.append(plato.toString()).append("\n");
            }
            JOptionPane.showMessageDialog(null, mensaje.toString(), "Platos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        SanducheDAO sanducheDAO = new SanducheDAO();

        List<Plato> sanduches = sanducheDAO.obtenerSanduches();

        if (sanduches.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se encontraron Sanduches.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            StringBuilder mensaje = new StringBuilder("Sanduches:\n");
            for (Plato sanduche : sanduches) {
                mensaje.append(sanduche.toString()).append("\n");
            }
            JOptionPane.showMessageDialog(null, mensaje.toString(), "Sanduches", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        EnsaladaDAO ensaladaDAO = new EnsaladaDAO();

        List<Plato> ensaladas = ensaladaDAO.obtenerEnsalada();

        if (ensaladas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se encontraron Ensaladas.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            StringBuilder mensaje = new StringBuilder("Ensaladas:\n");
            for (Plato ensalada : ensaladas) {
                mensaje.append(ensalada.toString()).append("\n");
            }
            JOptionPane.showMessageDialog(null, mensaje.toString(), "Ensaladas", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        dispose();               // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
